Basic HTTP Server and Initial Boilerplate Files
securemailbox/api pull request #13
Opened 2020-02-13 02:28 UTC by samgomena

This PR closes #7

2020-02-13 03:18 UTC, josephsPrograms approved these changes

2020-02-19 20:33 UTC, campyne requested changes
I put in the change to the docker run command you came up with the other night.

2020-02-19 20:33 UTC, campyne commented on README.md
> +docker run -it -p 8082:8082 securemailbox/api
```suggestion
docker run -it --network host -e DATABASE_URL=$DATABASE_URL -p 8082:8082 securemailbox/api
```

2020-02-25 03:43 UTC, samgomena commented on README.md
> +
Add docs about running on bare metal here.

2020-02-25 03:43 UTC, samgomena commented on securemailbox/__init__.py
> +
Check/ensure that python version is 3.6 +.

2020-02-25 03:43 UTC, samgomena commented on Pipfile
> +python_version = "3.8"
Update this to 3.6

2020-02-25 03:43 UTC, samgomena commented on securemailbox/__init__.py
> +
Possibly log a warning since pipenv will hard pin it to a min version.

2020-02-25 03:44 UTC, nvenetucci approved these changes

2020-02-25 03:44 UTC, Tom3424 approved these changes

2020-02-25 03:44 UTC, xingchengyusi approved these changes

2020-02-25 03:45 UTC, andrewbespaly approved these changes

2020-02-25 03:49 UTC, merged